name: Release notes

on:
  schedule:
    - cron: '0-50/5 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=$(expr $(date +%W) % 2)" >> $GITHUB_OUTPUT
        
  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: needs.job1.outputs.matrix == 0
    steps:
      - name: Semana par
        run: echo Esta es semana par

      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true
          ruby-version: 3.1.2
      - name: Bundle install
        run: |
          echo Initializing install
          bundle install
          echo everything installed!

