name: Release notes

on:
  schedule:
    - cron: '0-50/5 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=$(expr $(date +%W) % 2)" >> $GITHUB_OUTPUT
        
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Semana par
        if: $(("( $(date +%s) - $(date +%s --date=20220622) ) / 86400 % 14")) == 0
        run: |
          echo chi
          echo otra forma de comparar: $(("( $(date +%s) - $(date +%s --date=20220622) ) / 86400 % 14"))
          echo la condición es ${{$(("( $(date +%s) - $(date +%s --date=20220622) ) / 86400 % 14")) == 0}}
          echo La semana es $(expr $(date +%W) % 2)
          echo week = ${{needs.job1.outputs.matrix}}          
          echo Holi, esta semana es par, no hay release notes
          
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Semana impar
        if: ${{ needs.job1.outputs.matrix == 1}}
        run: |
          echo chi
          echo la condición es ${{needs.job1.outputs.matrix == 1}}
          echo La semana es $(expr $(date +%W) % 2)
          echo week = ${{needs.job1.outputs.matrix}}
          echo Holi, esta semana es impar, hay release notes
